#pragma once

enum class ActorDamageCause : int
{
    NONE = -1,
    OVERRIDE = 0,
    CONTACT = 1,
    ENTITYATTACK = 2,
    PROJECTILE = 3,
    SUFFOCATION = 4,
    FALL = 5,
    FIRE = 6,
    FIRETICK = 7,
    LAVA = 8,
    DROWNING = 9,
    BLOCKEXPLOSION = 10,
    ENTITYEXPLOSION = 11,
    VOID = 12,
    SELFDESTRUCT = 13,
    MAGIC = 14,
    WITHER = 15,
    STARVE = 16,
    ANVIL = 17,
    THORNS = 18,
    FALLINGBLOCK = 19,
    PISTON = 20,
    FLYINTOWALL = 21,
    MAGMA = 22,
    FIREWORKS = 23,
    LIGHTNING = 24,
    CHARGING = 25,
    TEMPERATURE = 26,
    FREEZING = 27,
    STALACTITE = 28,
    STALAGMITE = 29,
    RAMATTACK = 30,
    SONICBOOM = 31,
    CAMPFIRE = 32,
    SOULCAMPFIRE = 33,
    ALL = 34
};
